[package]
name = "pexec"
version = "0.1.0"
authors = ["psurapaneni@salesforce.com"]

[dependencies]
ssh2 = "0.2.8"
getopts = "0.2"
csv = "0.14.2"
rustc-serialize = "0.3.15"
num_cpus = "0.2.6"
rpassword = "0.0.5"
